python3 main_pretrain.py \
    --dataset cifar100 \
    --encoder resnet18 \
    --data_dir ./data \
    --train_dir train \
    --val_dir val \
    --max_epochs 500 \
    --devices 1 \
    --accelerator gpu \
    --precision 16 \
    --optimizer sgd \
    --lars \
    --grad_clip_lars \
    --eta_lars 0.02 \
    --exclude_bias_n_norm \
    --scheduler warmup_cosine \
    --lr 0.4 \
    --classifier_lr 0.1 \
    --weight_decay 1e-5 \
    --batch_size 256 \
    --num_workers 4 \
    --brightness 0.8 \
    --contrast 0.8 \
    --saturation 0.8 \
    --hue 0.2 \
    --gaussian_prob 0.0 0.0 \
    --min_scale 0.08 \
    --size 32 \
    --num_crops 2 \
    --name simclr-resnet18-cifar100 \
    --project cassle \
    --entity cassle_ssl \
    --save_checkpoint \
    --method simclr \
    --temperature 0.2 \
    --proj_hidden_dim 2048 \
    --output_dim 256 \
    --task_idx 0 \
    --split_strategy data \
    --num_tasks 1